# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "https://silver-concha-8aa40d.netlify.app/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}